name: colakg
channels:
  - nvidia
  - pytorch
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - altair=5.4.1=pyhd8ed1ab_3
  - asttokens=3.0.0=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - aws-c-auth=0.7.22=hf36ad8f_6
  - aws-c-cal=0.6.15=h816f305_1
  - aws-c-common=0.9.23=h4ab18f5_0
  - aws-c-compression=0.2.18=he027950_7
  - aws-c-event-stream=0.4.2=hb72ac1a_14
  - aws-c-http=0.8.2=h75ac8c9_3
  - aws-c-io=0.14.9=hd3d3696_3
  - aws-c-mqtt=0.10.4=hb0abfc5_7
  - aws-c-s3=0.5.10=h44b787d_4
  - aws-c-sdkutils=0.1.16=he027950_3
  - aws-checksums=0.1.18=he027950_7
  - aws-crt-cpp=0.26.12=he940a02_1
  - aws-sdk-cpp=1.11.329=h0f5bab0_6
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_4
  - backports.zoneinfo=0.2.1=py38h01eb140_8
  - blas=1.0=mkl
  - blinker=1.8.2=pyhd8ed1ab_0
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cachetools=5.5.0=pyhd8ed1ab_0
  - cffi=1.17.0=py38heb5c249_0
  - click=8.1.7=unix_pyh707e725_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cpython=3.8.20=py38hd8ed1ab_2
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - debugpy=1.8.5=py38h6d02427_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - ffmpeg=4.4.0=hca11adc_2
  - freetype=2.14.1=ha770c72_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py38h6a1700d_1
  - gnutls=3.6.13=h85f3911_1
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=78.1=h33c6efd_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.12.2=pyh41d4057_0
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240116.2=cxx17_he02047a_1
  - libarrow=16.1.0=h9102155_9_cpu
  - libarrow-acero=16.1.0=hac33072_9_cpu
  - libarrow-dataset=16.1.0=hac33072_9_cpu
  - libarrow-substrait=16.1.0=h7e0c224_9_cpu
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=16_linux64_mkl
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcurl=8.17.0=h4e3cde8_1
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - libgoogle-cloud=2.25.0=h2736e30_0
  - libgoogle-cloud-storage=2.25.0=h3d9a0c8_0
  - libgrpc=1.62.2=h15f2491_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libparquet=16.1.0=h6a7eafb_9_cpu
  - libpng=1.6.53=h421ea60_0
  - libprotobuf=4.25.3=hd5b35b9_1
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.51.1=hf4e2dac_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.5.0=h6adf6a1_2
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=2.41.3=h5347b49_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.4=hcb278e6_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py38h01eb140_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_0
  - narwhals=1.13.3=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - numpy=1.24.4=py38h59b608b_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.6.0=h26f9b46_0
  - orc=2.0.1=h17fec99_1
  - pandas=2.0.3=py38h01efb38_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.3.1=pyh8b19718_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - psutil=6.0.0=py38hfb59056_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pyarrow=16.1.0=py38hb563948_4
  - pyarrow-core=16.1.0=py38hed18a2d_4_cpu
  - pycparser=2.22=pyhd8ed1ab_0
  - pydeck=0.8.0=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.20=h4a871b0_2_cpython
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.8=8_cp38
  - pytorch=2.4.1=py3.8_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py38h2019614_0
  - pyzmq=26.2.0=py38h6c80b9a_0
  - re2=2023.09.01=h7f4b329_2
  - readline=8.3=h853b02a_0
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rich=13.9.4=pyhd8ed1ab_0
  - rpds-py=0.20.0=py38h4005ec7_0
  - s2n=1.4.16=he19d79f_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.2.2=h03e3b7b_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - streamlit=1.41.1=pyhd8ed1ab_0
  - sympy=1.13.3=pyh2585a3b_104
  - tenacity=9.0.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_ha0e22de_103
  - toml=0.10.2=pyhd8ed1ab_0
  - torchaudio=2.4.1=py38_cu121
  - torchtriton=3.0.0=py38
  - torchvision=0.20.0=py38_cu121
  - tornado=6.4.1=py38hfb59056_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzlocal=5.2=py38h578d9bd_0
  - watchdog=4.0.1=py38h578d9bd_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h75354e8_4
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.19.0=py38h0a891b7_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - filelock==3.15.4
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - huggingface-hub==0.24.5
      - idna==3.7
      - joblib==1.4.2
      - multidict==6.1.0
      - networkx==2.8.8
      - packaging==24.1
      - pillow==10.4.0
      - prettytable==3.11.0
      - protobuf==5.27.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - regex==2024.7.24
      - safetensors==0.4.4
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentence-transformers==3.0.1
      - setproctitle==1.3.3
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - tqdm==4.66.4
      - transformers==4.44.0
      - tzdata==2024.1
      - urllib3==2.2.2
      - yarl==1.11.1
